services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    # volumes:
    #   - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongoroot
      MONGO_INITDB_DATABASE: test
# volumes:
#   mongo_data:
#     driver: local